In [2]:
pip install numpy pandas matplotlib seaborn

Collecting numpy
  Using cached numpy-2.5.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting pandas
  Using cached pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\astroid\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.66.1-cp314-cp314-win_amd64.whl.metadata (132 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in e:\astroid\.venv\Lib\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: six>=1.5 in e:\astroid\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached numpy-2.5.3-cp314-cp314-win_amd64.whl (12.7 MB)
Using cached pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   -- ------------------------------------- 0.5/9.5 MB 110.4 kB/s eta 0:01:22
   --- ------------------------------------ 0.8/9.5 MB 116.3 kB/s eta 0:01:15
   --- ------------------------------------ 0.8/9.5 MB 116.3 kB/s eta 0:01:15
   --- ------------------------------------ 0.8/9.5 MB 116.3 kB/s eta 0:01:15
   --- ------------------------------------ 0.8/9.5 MB 116.3 kB/s eta 0:01:15
   --- ------------------------------------ 0.8/9.5 MB 116.3 kB/s eta 0:01:15
   --- ------------------------------------ 0.8/9.5 MB 116.3 kB/s eta 0:01:15
   --- ------------------------------------ 0.8/9.5 MB 116.3 kB/s eta 0:01:15
   ---- ----------------------------------- 1.0/9.5 MB 129.6 kB/s eta 0:01:06
   ---- ----------------------------------- 1.0/9.5 MB 129.6 kB/s eta 0:01:06
   ---- ----------------------------------- 1.0/9.5 MB 129.6 kB/s eta 0:01:06
   ---- ----------------------------------- 1.0/9.5 MB 129.6 kB/s eta 0:01:06
   ---- ----------------------------------- 1.0/9.5 MB 129.6 kB/s eta 0:01:06
   ---- ----------------------------------- 1.0/9.5 MB 129.6 kB/s eta 0:01:06
   ----- ---------------------------------- 1.3/9.5 MB 143.6 kB/s eta 0:00:58
   ----- ---------------------------------- 1.3/9.5 MB 143.6 kB/s eta 0:00:58
   ------ --------------------------------- 1.6/9.5 MB 169.5 kB/s eta 0:00:47
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   ------- -------------------------------- 1.8/9.5 MB 196.1 kB/s eta 0:00:40
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   -------- ------------------------------- 2.1/9.5 MB 79.0 kB/s eta 0:01:34
   --------- ------------------------------ 2.4/9.5 MB 75.1 kB/s eta 0:01:36
   ----------- ---------------------------- 2.6/9.5 MB 83.8 kB/s eta 0:01:23
   ------------ --------------------------- 2.9/9.5 MB 92.5 kB/s eta 0:01:12
   ------------- -------------------------- 3.1/9.5 MB 100.8 kB/s eta 0:01:04
   -------------- ------------------------- 3.4/9.5 MB 109.0 kB/s eta 0:00:56
   -------------- ------------------------- 3.4/9.5 MB 109.0 kB/s eta 0:00:56
   --------------- ------------------------ 3.7/9.5 MB 116.8 kB/s eta 0:00:50
   ---------------- ----------------------- 3.9/9.5 MB 124.5 kB/s eta 0:00:45
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ----------------- ---------------------- 4.2/9.5 MB 132.6 kB/s eta 0:00:41
   ------------------ --------------------- 4.5/9.5 MB 133.5 kB/s eta 0:00:38
   ------------------ --------------------- 4.5/9.5 MB 133.5 kB/s eta 0:00:38
   ------------------ --------------------- 4.5/9.5 MB 133.5 kB/s eta 0:00:38
   ------------------- -------------------- 4.7/9.5 MB 141.1 kB/s eta 0:00:34
   ---------------------- ----------------- 5.2/9.5 MB 158.1 kB/s eta 0:00:27
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ----------------------- ---------------- 5.5/9.5 MB 166.9 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.5 MB 149.2 kB/s eta 0:00:26
   ------------------------ --------------- 5.8/9.5 MB 149.2 kB/s eta 0:00:26
   ------------------------ --------------- 5.8/9.5 MB 149.2 kB/s eta 0:00:26
   ------------------------ --------------- 5.8/9.5 MB 149.2 kB/s eta 0:00:26
   ------------------------ --------------- 5.8/9.5 MB 149.2 kB/s eta 0:00:26
   --------------------------- ------------ 6.6/9.5 MB 297.2 kB/s eta 0:00:10
   ------------------------------- -------- 7.6/9.5 MB 360.9 kB/s eta 0:00:06
   ---------------------------------- ----- 8.1/9.5 MB 391.5 kB/s eta 0:00:04
   ------------------------------------ --- 8.7/9.5 MB 420.8 kB/s eta 0:00:03
   ------------------------------------- -- 8.9/9.5 MB 434.0 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 444.9 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 451.3 kB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 453.1 kB/s  0:00:41
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl (240 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.66.1-cp314-cp314-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.5 MB 86.8 kB/s eta 0:00:23
   -------- ------------------------------- 0.5/2.5 MB 86.8 kB/s eta 0:00:23
   ------------ --------------------------- 0.8/2.5 MB 152.6 kB/s eta 0:00:12
   ------------ --------------------------- 0.8/2.5 MB 152.6 kB/s eta 0:00:12
   ---------------- ----------------------- 1.0/2.5 MB 199.6 kB/s eta 0:00:08
   ---------------- ----------------------- 1.0/2.5 MB 199.6 kB/s eta 0:00:08
   ---------------- ----------------------- 1.0/2.5 MB 199.6 kB/s eta 0:00:08
   ---------------- ----------------------- 1.0/2.5 MB 199.6 kB/s eta 0:00:08
   ---------------- ----------------------- 1.0/2.5 MB 199.6 kB/s eta 0:00:08

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv('../data/raw/pha_dataset.csv')

print("Dataset loaded")
print("Shape:", df.shape)

C:\Users\surek\AppData\Local\Temp\ipykernel_13884\3140300387.py:1: DtypeWarning: Columns (3: pdes, 4: name, 5: prefix) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/pha_dataset.csv')

Dataset loaded
Shape: (958524, 45)

In [5]:
df.head()

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,albedo,diameter_sigma,orbit_id,epoch,epoch_mjd,epoch_cal,equinox,e,a,q,i,om,w,ma,ad,n,tp,tp_cal,per,per_y,moid,moid_ld,sigma_e,sigma_a,sigma_q,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.40,939.400,0.0900,0.200,JPL 47,2458600.5,58600,20190427.0,J2000,0.076009,2.769165,2.558684,10.594067,80.305531,73.597695,77.372098,2.979647,0.213885,2.458239e+06,2.018043e+07,1683.145703,4.608202,1.59478,620.640533,4.819000e-12,1.032800e-11,1.956900e-11,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,MBA,0.43301
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.20,545.000,0.1010,18.000,JPL 37,2459000.5,59000,20200531.0,J2000,0.229972,2.773841,2.135935,34.832932,173.024741,310.202392,144.975675,3.411748,0.213345,2.458321e+06,2.018072e+07,1687.410992,4.619880,1.23429,480.348639,3.193400e-08,4.033700e-09,8.832200e-08,3.469400e-06,6.272400e-06,9.128200e-06,8.859100e-06,4.961300e-09,4.653600e-10,4.078700e-05,3.680700e-06,MBA,0.35936
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.33,246.596,0.2140,10.594,JPL 112,2459000.5,59000,20200531.0,J2000,0.256936,2.668285,1.982706,12.991043,169.851482,248.066193,125.435355,3.353865,0.226129,2.458446e+06,2.018112e+07,1592.013769,4.358696,1.03429,402.514639,3.052000e-08,3.471800e-09,8.139200e-08,3.223100e-06,1.664600e-05,1.772100e-05,8.110400e-06,4.363900e-09,4.413400e-10,3.528800e-05,3.107200e-06,MBA,0.33848
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.00,525.400,0.4228,0.200,JPL 35,2458600.5,58600,20190427.0,J2000,0.088721,2.361418,2.151909,7.141771,103.810804,150.728541,95.861938,2.570926,0.271609,2.458248e+06,2.018051e+07,1325.432763,3.628837,1.13948,443.451432,2.332100e-10,1.514300e-09,1.928600e-09,2.170600e-07,3.880800e-07,1.789300e-07,1.206800e-06,1.648600e-09,2.612500e-10,4.103700e-06,1.274900e-06,MBA,0.39980
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.90,106.699,0.2740,3.140,JPL 114,2459000.5,59000,20200531.0,J2000,0.190913,2.574037,2.082619,5.367427,141.571026,358.648418,17.846343,3.065455,0.238661,2.458926e+06,2.020032e+07,1508.414421,4.129814,1.09575,426.433027,2.373700e-08,3.970900e-09,6.092400e-08,2.740800e-06,2.894900e-05,2.984200e-05,8.303800e-06,4.729000e-09,5.522700e-10,3.474300e-05,3.490500e-06,MBA,0.52191

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 958524 entries, 0 to 958523
Data columns (total 45 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              958524 non-null  str
 1   spkid           958524 non-null  int64
 2   full_name       958524 non-null  str
 3   pdes            958524 non-null  object
 4   name            22064 non-null   str
 5   prefix          18 non-null      str
 6   neo             958520 non-null  str
 7   pha             938603 non-null  str
 8   H               952261 non-null  float64
 9   diameter        136209 non-null  float64
 10  albedo          135103 non-null  float64
 11  diameter_sigma  136081 non-null  float64
 12  orbit_id        958524 non-null  str
 13  epoch           958524 non-null  float64
 14  epoch_mjd       958524 non-null  int64
 15  epoch_cal       958524 non-null  float64
 16  equinox         958524 non-null  str
 17  e               958524 non-null  float64
 18  a               958524 non-null  float64
 19  q               958524 non-null  float64
 20  i               958524 non-null  float64
 21  om              958524 non-null  float64
 22  w               958524 non-null  float64
 23  ma              958523 non-null  float64
 24  ad              958520 non-null  float64
 25  n               958524 non-null  float64
 26  tp              958524 non-null  float64
 27  tp_cal          958524 non-null  float64
 28  per             958520 non-null  float64
 29  per_y           958523 non-null  float64
 30  moid            938603 non-null  float64
 31  moid_ld         958397 non-null  float64
 32  sigma_e         938602 non-null  float64
 33  sigma_a         938602 non-null  float64
 34  sigma_q         938602 non-null  float64
 35  sigma_i         938602 non-null  float64
 36  sigma_om        938602 non-null  float64
 37  sigma_w         938602 non-null  float64
 38  sigma_ma        938602 non-null  float64
 39  sigma_ad        938598 non-null  float64
 40  sigma_n         938602 non-null  float64
 41  sigma_tp        938602 non-null  float64
 42  sigma_per       938598 non-null  float64
 43  class           958524 non-null  str
 44  rms             958522 non-null  float64
dtypes: float64(33), int64(2), object(1), str(9)
memory usage: 329.1+ MB

In [7]:
df.describe()

,spkid,H,diameter,albedo,diameter_sigma,epoch,epoch_mjd,epoch_cal,e,a,q,i,om,w,ma,ad,n,tp,tp_cal,per,per_y,moid,moid_ld,sigma_e,sigma_a,sigma_q,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,rms
count,9.585240e+05,952261.000000,136209.000000,135103.000000,136081.000000,9.585240e+05,958524.000000,9.585240e+05,958524.000000,958524.000000,958524.000000,958524.000000,958524.000000,958524.000000,958523.000000,958520.000000,9.585240e+05,9.585240e+05,9.585240e+05,9.585200e+05,9.585230e+05,9.386030e+05,958397.000000,9.386020e+05,9.386020e+05,9.386020e+05,9.386020e+05,9.386020e+05,9.386020e+05,9.386020e+05,9.385980e+05,9.386020e+05,9.386020e+05,9.385980e+05,958522.000000
mean,3.810114e+06,16.906411,5.506429,0.130627,0.479184,2.458869e+06,58868.781950,2.019693e+07,0.156116,2.902143,2.394887,9.054901,168.456416,181.369457,177.352582,3.455820,2.366846e-01,2.458856e+06,2.019581e+07,5.085344e+03,1.392287e+01,1.415162e+00,539.364207,7.262721e-01,1.541424e+01,1.982929e+01,1.168449e+00,5.310234e+00,1.370062e+06,1.369977e+06,2.131453e+01,5.060221e-02,4.312780e+08,8.525815e+04,0.561153
std,6.831541e+06,1.790405,9.425164,0.110323,0.782895,7.016716e+02,701.671573,1.930354e+04,0.092643,39.719503,2.139246,6.637656,102.881707,103.887995,105.816844,71.769401,7.941705e-02,1.580506e+03,4.337669e+04,2.308961e+06,6.321581e+03,2.156731e+00,834.306975,9.336391e+01,4.392381e+03,2.903785e+03,1.282231e+02,1.333381e+03,9.158996e+08,9.158991e+08,7.197034e+03,9.814953e+00,2.953046e+11,2.767681e+07,2.745700
min,2.000001e+06,-1.100000,0.002500,0.001000,0.000500,2.425052e+06,25051.000000,1.927062e+07,0.000000,-14702.447872,0.070511,0.007744,0.000025,0.000130,-70.703676,0.653773,1.608247e-07,2.283183e+06,1.539011e+07,1.511918e+02,0.000000e+00,4.544120e-07,0.000000,4.819000e-12,1.032800e-11,1.956900e-11,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,0.000000
25%,2.239632e+06,16.100000,2.780000,0.053000,0.180000,2.459000e+06,59000.000000,2.020053e+07,0.092193,2.387835,1.971401,4.165419,80.604399,91.482063,83.785012,2.781603,1.894969e-01,2.458560e+06,2.019032e+07,1.347738e+03,3.689903e+00,9.797020e-01,375.394939,5.474900e-08,2.046500e-08,1.462000e-07,6.095900e-06,3.619400e-05,5.755000e-05,2.573700e-05,2.340900e-08,2.768800e-09,1.110900e-04,1.794500e-05,0.518040
50%,2.479262e+06,16.900000,3.972000,0.079000,0.332000,2.459000e+06,59000.000000,2.020053e+07,0.145002,2.646969,2.225816,7.415665,159.826919,182.358081,175.641078,3.046995,2.288655e-01,2.458945e+06,2.020041e+07,1.572976e+03,4.306571e+00,1.240850e+00,477.706175,8.171600e-08,3.849150e-08,2.271900e-07,8.688800e-06,6.642550e-05,1.047100e-04,4.900100e-05,4.359000e-08,4.638000e-09,2.230800e-04,3.501700e-05,0.566280
75%,3.752518e+06,17.714000,5.765000,0.190000,0.620000,2.459000e+06,59000.000000,2.020053e+07,0.200650,3.001932,2.578315,12.407550,252.247751,271.521589,269.865749,3.364793,2.671142e-01,2.459361e+06,2.021053e+07,1.899765e+03,5.201272e+00,1.593370e+00,617.324804,2.336475e-07,1.044675e-07,6.583200e-07,1.591500e-05,1.609775e-04,3.114400e-04,1.718900e-04,1.196600e-07,1.124000e-08,8.139600e-04,9.775475e-05,0.613927
max,5.401723e+07,33.200000,939.400000,1.000000,140.000000,2.459000e+06,59000.000000,2.020053e+07,1.855356,33488.895955,80.398819,175.082901,359.999793,359.999646,491.618014,66972.796064,2.381082e+00,2.546362e+06,2.259081e+07,2.238462e+09,6.128574e+06,7.947660e+01,30929.908422,3.942500e+04,3.241200e+06,1.015000e+06,5.533000e+04,1.199100e+06,8.845100e+11,8.845100e+11,5.509700e+06,7.698800e+03,2.853100e+14,1.910700e+10,2686.600000

In [8]:

print("Total columns:", len(df.columns))
print("\nAll columns:")

for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

Total columns: 45

All columns:
1. id
2. spkid
3. full_name
4. pdes
5. name
6. prefix
7. neo
8. pha
9. H
10. diameter
11. albedo
12. diameter_sigma
13. orbit_id
14. epoch
15. epoch_mjd
16. epoch_cal
17. equinox
18. e
19. a
20. q
21. i
22. om
23. w
24. ma
25. ad
26. n
27. tp
28. tp_cal
29. per
30. per_y
31. moid
32. moid_ld
33. sigma_e
34. sigma_a
35. sigma_q
36. sigma_i
37. sigma_om
38. sigma_w
39. sigma_ma
40. sigma_ad
41. sigma_n
42. sigma_tp
43. sigma_per
44. class
45. rms

In [9]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print("Columns with missing values:", len(missing))
print("\nMissing values:")
print(missing)

Columns with missing values: 26

Missing values:
prefix            958506
name              936460
albedo            823421
diameter_sigma    822443
diameter          822315
sigma_per          19926
sigma_ad           19926
sigma_i            19922
sigma_q            19922
sigma_om           19922
sigma_ma           19922
sigma_n            19922
sigma_tp           19922
sigma_e            19922
sigma_a            19922
sigma_w            19922
pha                19921
moid               19921
H                   6263
moid_ld              127
neo                    4
ad                     4
per                    4
rms                    2
ma                     1
per_y                  1
dtype: int64

In [ ]:
dup_count = df.duplicated().sum()
print("Duplicate rows:", dup_count)

Duplicate rows: 0

In [11]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print("Numeric columns:", len(numeric_cols))
print(numeric_cols)

print("\nCategorical columns:", len(categorical_cols))
print(categorical_cols)

Numeric columns: 35
['spkid', 'H', 'diameter', 'albedo', 'diameter_sigma', 'epoch', 'epoch_mjd', 'epoch_cal', 'e', 'a', 'q', 'i', 'om', 'w', 'ma', 'ad', 'n', 'tp', 'tp_cal', 'per', 'per_y', 'moid', 'moid_ld', 'sigma_e', 'sigma_a', 'sigma_q', 'sigma_i', 'sigma_om', 'sigma_w', 'sigma_ma', 'sigma_ad', 'sigma_n', 'sigma_tp', 'sigma_per', 'rms']

Categorical columns: 10
['id', 'full_name', 'pdes', 'name', 'prefix', 'neo', 'pha', 'orbit_id', 'equinox', 'class']

C:\Users\surek\AppData\Local\Temp\ipykernel_13884\518092005.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

In [14]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print("Numeric columns:", len(numeric_cols))
print(numeric_cols)

print("\nCategorical columns:", len(categorical_cols))
print(categorical_cols)

Numeric columns: 35
['spkid', 'H', 'diameter', 'albedo', 'diameter_sigma', 'epoch', 'epoch_mjd', 'epoch_cal', 'e', 'a', 'q', 'i', 'om', 'w', 'ma', 'ad', 'n', 'tp', 'tp_cal', 'per', 'per_y', 'moid', 'moid_ld', 'sigma_e', 'sigma_a', 'sigma_q', 'sigma_i', 'sigma_om', 'sigma_w', 'sigma_ma', 'sigma_ad', 'sigma_n', 'sigma_tp', 'sigma_per', 'rms']

Categorical columns: 10
['id', 'full_name', 'pdes', 'name', 'prefix', 'neo', 'pha', 'orbit_id', 'equinox', 'class']

C:\Users\surek\AppData\Local\Temp\ipykernel_13884\3280647428.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

In [15]:
#target 1 pha
print("PHA value counts:")
print(df['pha'].value_counts())

print("\nPHA percentage:")
print(df['pha'].value_counts(normalize=True) * 100)

PHA value counts:
pha
N    936537
Y      2066
Name: count, dtype: int64

PHA percentage:
pha
N    99.779886
Y     0.220114
Name: proportion, dtype: float64

In [13]:
#target 2 diamter
print("Diameter statistics:")
print(df['diameter'].describe())

Diameter statistics:
count    136209.000000
mean          5.506429
std           9.425164
min           0.002500
25%           2.780000
50%           3.972000
75%           5.765000
max         939.400000
Name: diameter, dtype: float64

In [16]:
#NEO & Class Check
if 'neo' in df.columns:
    print("NEO value counts:")
    print(df['neo'].value_counts())
    print()

if 'class' in df.columns:
    print("Orbit class value counts:")
    print(df['class'].value_counts().head(10))

NEO value counts:
neo
N    935625
Y     22895
Name: count, dtype: int64

Orbit class value counts:
class
MBA    855954
OMB     28355
IMB     20360
MCA     18685
APO     12687
AMO      8457
TJN      8221
TNO      3468
ATE      1729
CEN       506
Name: count, dtype: int64

In [18]:

print("DATASET SUMMARY")

print(f"Total rows: {df.shape[0]}")
print(f"Total columns: {df.shape[1]}")
print(f"Numeric columns: {len(numeric_cols)}")
print(f"Categorical columns: {len(categorical_cols)}")
print(f"Columns with missing values: {len(missing)}")
print(f"Duplicate rows: {dup_count}")

DATASET SUMMARY
Total rows: 958524
Total columns: 45
Numeric columns: 35
Categorical columns: 10
Columns with missing values: 26
Duplicate rows: 0

In [ ]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print("Columns with missing values:", len(missing))
print("\nMissing values:")
print(missing)

#>80 % missing values

#> 50%	Drop column
#10-50%	Drop column 
#2-10%	Impute (mean/median/mode)
#< 2%	Drop rows (or impute)

Columns with missing values: 26

Missing values:
prefix            958506
name              936460
albedo            823421
diameter_sigma    822443
diameter          822315
sigma_per          19926
sigma_ad           19926
sigma_i            19922
sigma_q            19922
sigma_om           19922
sigma_ma           19922
sigma_n            19922
sigma_tp           19922
sigma_e            19922
sigma_a            19922
sigma_w            19922
pha                19921
moid               19921
H                   6263
moid_ld              127
neo                    4
ad                     4
per                    4
rms                    2
ma                     1
per_y                  1
dtype: int64